src/main/java/edu/umm/radonc/ca_dash/model/Activityinstance.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.umm.radonc.ca_dash.model;

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author mmcgrath
 */
@Entity
@Table(name = "activityinstance")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Activityinstance.findAll", query = "SELECT a FROM Activityinstance a"),
    @NamedQuery(name = "Activityinstance.findByActivityinstanceser", query = "SELECT a FROM Activityinstance a WHERE a.activityinstanceser = :activityinstanceser"),
    @NamedQuery(name = "Activityinstance.findByObjectstatus", query = "SELECT a FROM Activityinstance a WHERE a.objectstatus = :objectstatus"),
    @NamedQuery(name = "Activityinstance.findByDuration", query = "SELECT a FROM Activityinstance a WHERE a.duration = :duration"),
    @NamedQuery(name = "Activityinstance.findByHstrydatetime", query = "SELECT a FROM Activityinstance a WHERE a.hstrydatetime = :hstrydatetime")})
public class Activityinstance implements Serializable {
    @Column(name = "activityser")
    private Integer activityser;
    @Column(name = "departmentser")
    private Integer departmentser;
    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Column(name = "activityinstanceser")
    private Integer activityinstanceser;
    @Size(max = 25)
    @Column(name = "objectstatus")
    private String objectstatus;
    @Column(name = "duration")
    private Integer duration;
    @Column(name = "hstrydatetime")
    @Temporal(TemporalType.DATE)
    private Date hstrydatetime;
    /*@JoinColumn(name = "activityser", referencedColumnName = "activityser")
    @ManyToOne
    private Activity activityser;
    @JoinColumn(name = "departmentser", referencedColumnName = "departmentser")
    @ManyToOne
    private Department departmentser;*/
    //@OneToMany(mappedBy = "activityinstanceser")
    //private Collection<Activitycapture> activitycaptureCollection;

    public Activityinstance() {
    }

    public Activityinstance(Integer activityinstanceser) {
        this.activityinstanceser = activityinstanceser;
    }

    public Integer getActivityinstanceser() {
        return activityinstanceser;
    }

    public void setActivityinstanceser(Integer activityinstanceser) {
        this.activityinstanceser = activityinstanceser;
    }

    public String getObjectstatus() {
        return objectstatus;
    }

    public void setObjectstatus(String objectstatus) {
        this.objectstatus = objectstatus;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public Date getHstrydatetime() {
        return hstrydatetime;
    }

    public void setHstrydatetime(Date hstrydatetime) {
        this.hstrydatetime = hstrydatetime;
    }

    /*public Activity getActivityser() {
        return activityser;
    }

    public void setActivityser(Activity activityser) {
        this.activityser = activityser;
    }

    public Department getDepartmentser() {
        return departmentser;
    }

    public void setDepartmentser(Department departmentser) {
        this.departmentser = departmentser;
    }*/

    /*@XmlTransient
    public Collection<Activitycapture> getActivitycaptureCollection() {
        return activitycaptureCollection;
    }

    public void setActivitycaptureCollection(Collection<Activitycapture> activitycaptureCollection) {
        this.activitycaptureCollection = activitycaptureCollection;
    }*/

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (activityinstanceser != null ? activityinstanceser.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Activityinstance)) {
            return false;
        }
        Activityinstance other = (Activityinstance) object;
        if ((this.activityinstanceser == null && other.activityinstanceser != null) || (this.activityinstanceser != null && !this.activityinstanceser.equals(other.activityinstanceser))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "edu.umm.radonc.ca_dash.model.Activityinstance[ activityinstanceser=" + activityinstanceser + " ]";
    }

    public Integer getActivityser() {
        return activityser;
    }

    public void setActivityser(Integer activityser) {
        this.activityser = activityser;
    }

    public Integer getDepartmentser() {
        return departmentser;
    }

    public void setDepartmentser(Integer departmentser) {
        this.departmentser = departmentser;
    }
    
}

src/main/java/edu/umm/radonc/ca_dash/controllers/ActivityinstanceController.java
package edu.umm.radonc.ca_dash.controllers;

import edu.umm.radonc.ca_dash.model.Activityinstance;
import edu.umm.radonc.ca_dash.controllers.util.JsfUtil;
import edu.umm.radonc.ca_dash.controllers.util.JsfUtil.PersistAction;
import edu.umm.radonc.ca_dash.model.ActivityinstanceFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("activityinstanceController")
@SessionScoped
public class ActivityinstanceController implements Serializable {

    @EJB
    private edu.umm.radonc.ca_dash.model.ActivityinstanceFacade ejbFacade;
    private List<Activityinstance> items = null;
    private Activityinstance selected;

    public ActivityinstanceController() {
    }

    public Activityinstance getSelected() {
        return selected;
    }

    public void setSelected(Activityinstance selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private ActivityinstanceFacade getFacade() {
        return ejbFacade;
    }

    public Activityinstance prepareCreate() {
        selected = new Activityinstance();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("ActivityinstanceCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("ActivityinstanceUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("ActivityinstanceDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Activityinstance> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Activityinstance getActivityinstance(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Activityinstance> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Activityinstance> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Activityinstance.class)
    public static class ActivityinstanceControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ActivityinstanceController controller = (ActivityinstanceController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "activityinstanceController");
            return controller.getActivityinstance(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Activityinstance) {
                Activityinstance o = (Activityinstance) object;
                return getStringKey(o.getActivityinstanceser());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Activityinstance.class.getName()});
                return null;
            }
        }

    }

}

src/main/webapp/activityinstance/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ActivityinstanceCreateDlg" widgetVar="ActivityinstanceCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateActivityinstanceTitle}">
            <h:form id="ActivityinstanceCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{activityinstanceController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateActivityinstanceLabel_activityinstanceser}" for="activityinstanceser" />
                        <p:inputText id="activityinstanceser" value="#{activityinstanceController.selected.activityinstanceser}" title="#{bundle.CreateActivityinstanceTitle_activityinstanceser}" required="true" requiredMessage="#{bundle.CreateActivityinstanceRequiredMessage_activityinstanceser}"/>
                        <p:outputLabel value="#{bundle.CreateActivityinstanceLabel_objectstatus}" for="objectstatus" />
                        <p:inputText id="objectstatus" value="#{activityinstanceController.selected.objectstatus}" title="#{bundle.CreateActivityinstanceTitle_objectstatus}" />
                        <p:outputLabel value="#{bundle.CreateActivityinstanceLabel_duration}" for="duration" />
                        <p:inputText id="duration" value="#{activityinstanceController.selected.duration}" title="#{bundle.CreateActivityinstanceTitle_duration}" />
                        <p:outputLabel value="#{bundle.CreateActivityinstanceLabel_hstrydatetime}" for="hstrydatetime" />
                        <p:calendar id="hstrydatetime" pattern="MM/dd/yyyy" value="#{activityinstanceController.selected.hstrydatetime}" title="#{bundle.EditActivityinstanceTitle_hstrydatetime}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.CreateActivityinstanceLabel_activityser}" for="activityser" />
                        <p:selectOneMenu id="activityser" value="#{activityinstanceController.selected.activityser}" >
                            <f:selectItems value="#{activityController.itemsAvailableSelectOne}"
                                           var="activityserItem"
                                           itemValue="#{activityserItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateActivityinstanceLabel_departmentser}" for="departmentser" />
                        <p:selectOneMenu id="departmentser" value="#{activityinstanceController.selected.departmentser}" >
                            <f:selectItems value="#{departmentController.itemsAvailableSelectOne}"
                                           var="departmentserItem"
                                           itemValue="#{departmentserItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{activityinstanceController.create}" value="#{bundle.Save}" update="display,:ActivityinstanceListForm:datalist,:growl" oncomplete="handleSubmit(args,'ActivityinstanceCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ActivityinstanceCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/activityinstance/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ActivityinstanceEditDlg" widgetVar="ActivityinstanceEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditActivityinstanceTitle}">
            <h:form id="ActivityinstanceEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{activityinstanceController.selected != null}">
                        <p:outputLabel value="#{bundle.EditActivityinstanceLabel_activityinstanceser}" for="activityinstanceser" />
                        <p:inputText id="activityinstanceser" value="#{activityinstanceController.selected.activityinstanceser}" title="#{bundle.EditActivityinstanceTitle_activityinstanceser}" required="true" requiredMessage="#{bundle.EditActivityinstanceRequiredMessage_activityinstanceser}"/>
                        <p:outputLabel value="#{bundle.EditActivityinstanceLabel_objectstatus}" for="objectstatus" />
                        <p:inputText id="objectstatus" value="#{activityinstanceController.selected.objectstatus}" title="#{bundle.EditActivityinstanceTitle_objectstatus}" />
                        <p:outputLabel value="#{bundle.EditActivityinstanceLabel_duration}" for="duration" />
                        <p:inputText id="duration" value="#{activityinstanceController.selected.duration}" title="#{bundle.EditActivityinstanceTitle_duration}" />
                        <p:outputLabel value="#{bundle.EditActivityinstanceLabel_hstrydatetime}" for="hstrydatetime" />
                        <p:calendar id="hstrydatetime" pattern="MM/dd/yyyy" value="#{activityinstanceController.selected.hstrydatetime}" title="#{bundle.EditActivityinstanceTitle_hstrydatetime}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.EditActivityinstanceLabel_activityser}" for="activityser" />
                        <p:selectOneMenu id="activityser" value="#{activityinstanceController.selected.activityser}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{activityController.itemsAvailableSelectOne}"
                                           var="activityserItem"
                                           itemValue="#{activityserItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditActivityinstanceLabel_departmentser}" for="departmentser" />
                        <p:selectOneMenu id="departmentser" value="#{activityinstanceController.selected.departmentser}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{departmentController.itemsAvailableSelectOne}"
                                           var="departmentserItem"
                                           itemValue="#{departmentserItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{activityinstanceController.update}" value="#{bundle.Save}" update="display,:ActivityinstanceListForm:datalist,:growl" oncomplete="handleSubmit(args, 'ActivityinstanceEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ActivityinstanceEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/activityinstance/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListActivityinstanceTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="ActivityinstanceListForm">
                <p:panel header="#{bundle.ListActivityinstanceTitle}">
                    <p:dataTable id="datalist" value="#{activityinstanceController.items}" var="item"
                                 selectionMode="single" selection="#{activityinstanceController.selected}"
                                 paginator="true"
                                 rowKey="#{item.activityinstanceser}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListActivityinstanceTitle_activityinstanceser}"/>
                            </f:facet>
                            <h:outputText value="#{item.activityinstanceser}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListActivityinstanceTitle_objectstatus}"/>
                            </f:facet>
                            <h:outputText value="#{item.objectstatus}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListActivityinstanceTitle_duration}"/>
                            </f:facet>
                            <h:outputText value="#{item.duration}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListActivityinstanceTitle_hstrydatetime}"/>
                            </f:facet>
                            <h:outputText value="#{item.hstrydatetime}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListActivityinstanceTitle_activityser}"/>
                            </f:facet>
                            <h:outputText value="#{item.activityser}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListActivityinstanceTitle_departmentser}"/>
                            </f:facet>
                            <h:outputText value="#{item.departmentser}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{activityinstanceController.prepareCreate}" update=":ActivityinstanceCreateForm" oncomplete="PF('ActivityinstanceCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":ActivityinstanceViewForm" oncomplete="PF('ActivityinstanceViewDialog').show()" disabled="#{empty activityinstanceController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":ActivityinstanceEditForm" oncomplete="PF('ActivityinstanceEditDialog').show()" disabled="#{empty activityinstanceController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{activityinstanceController.destroy}" update=":growl,datalist" disabled="#{empty activityinstanceController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/activityinstance/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ActivityinstanceViewDlg" widgetVar="ActivityinstanceViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewActivityinstanceTitle}">
            <h:form id="ActivityinstanceViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{activityinstanceController.selected != null}">
                        <h:outputText value="#{bundle.ViewActivityinstanceLabel_activityinstanceser}"/>
                        <h:outputText value="#{activityinstanceController.selected.activityinstanceser}" title="#{bundle.ViewActivityinstanceTitle_activityinstanceser}"/>
                        <h:outputText value="#{bundle.ViewActivityinstanceLabel_objectstatus}"/>
                        <h:outputText value="#{activityinstanceController.selected.objectstatus}" title="#{bundle.ViewActivityinstanceTitle_objectstatus}"/>
                        <h:outputText value="#{bundle.ViewActivityinstanceLabel_duration}"/>
                        <h:outputText value="#{activityinstanceController.selected.duration}" title="#{bundle.ViewActivityinstanceTitle_duration}"/>
                        <h:outputText value="#{bundle.ViewActivityinstanceLabel_hstrydatetime}"/>
                        <h:outputText value="#{activityinstanceController.selected.hstrydatetime}" title="#{bundle.ViewActivityinstanceTitle_hstrydatetime}">
                            <f:convertDateTime pattern="MM/dd/yyyy" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewActivityinstanceLabel_activityser}"/>
                        <h:outputText value="#{activityinstanceController.selected.activityser}" title="#{bundle.ViewActivityinstanceTitle_activityser}"/>
                        <h:outputText value="#{bundle.ViewActivityinstanceLabel_departmentser}"/>
                        <h:outputText value="#{activityinstanceController.selected.departmentser}" title="#{bundle.ViewActivityinstanceTitle_departmentser}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="ActivityinstanceViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>